### ISSUE TITLE
Disaster Form Style ?

### ISSUE THREAD

**Issue by vincentsarago** [vincentsarago/disasterwatch#14]
I set up a first form to add disaster info! 

![capture d ecran 2016-09-07 a 22 34 12](https://cloud.githubusercontent.com/assets/10407788/18335464/83600c42-754d-11e6-918f-f6db45c622f8.png)

I tried to add general disaster tag, but if someone want's to add one I'm all open. 
![capture d ecran 2016-09-07 a 22 33 40](https://cloud.githubusercontent.com/assets/10407788/18335465/85a5a1c4-754d-11e6-8050-cba58ccfdf81.png)

About the style, it's really basic so I may ask to a someone handy in design to provide some icons!

**Comment by vincentsarago** [comment]
it will be nice I think to add icons to make disaster type more visual!
Also, icons would be nice on the map! 

To Do:
- [x] set the disaster types list
- [x] design svg icons
- [ ] add icons on mapbox-studio / create mapbox gl sprite seems really hard (https://www.mapbox.com/help/define-sprite/)
- [ ] add icons on map for each disaster (also for EONet Events)

**Comment by ghost** [comment]
I volunteer for designing the SVG icons; I have a few days off this week, so should be able to put some time into it.

**Comment by vincentsarago** [comment]
@CodeMacabre thanks so much :-) 
let me know if you need some inputs !

**Comment by ghost** [comment]
What do you think of these early tests? I'm experimenting with a coloured circular theme, but they could easily be converted to monochrome, other shapes, etc.

Earthquake:
![earthquake](https://cloud.githubusercontent.com/assets/19981049/19132683/ae804db4-8b4c-11e6-9dce-b0a763578af3.jpg)

Tsunami:
![tsunami](https://cloud.githubusercontent.com/assets/19981049/19132681/ae25394c-8b4c-11e6-8065-97166622e0ab.jpg)

**Comment by vincentsarago** [comment]
whooooooaaa that's awesome 👍

**Comment by ghost** [comment]
Excellent, glad to know I'm on the right path! I hope to spend some time over the weekend getting a full set of first drafts finished. Do you have any ideas or suggestions for the 'other / uncategorised' icon? I was thinking something like the generic hazard / caution symbol ⚠.

**Comment by vincentsarago** [comment]
Do as you want :-), the generic hazard is good 👍

**Comment by ghost** [comment]
@vincentsarago Just a heads-up, most icons drafted but I'm away from my PC for a few days. Should be able to get them to you Thursday.

**Comment by vincentsarago** [comment]
@CodeMacabre no rush! I'm working on the DB part and that could be long :-)

**Comment by ghost** [comment]
I just discovered [this set of humanitarian icons](http://mw1.google.com/crisisresponse/icons/un-ocha/index.html#cat_disaster) by the UN OCHA. There's also a web font [here](https://github.com/lubar/Humanitarian-Icons-WebFont), which includes them in SVG format.

It renders what I've been working on a bit obsolete, but as these are a recognised / established standard, it may be best to use them instead. What do you think?

**Comment by vincentsarago** [comment]
@CodeMacabre I knew those, but they are png and I really wanted something from scratch! but if you think those are better, it's ok!

**Comment by ghost** [comment]
Ah ok, if you prefer custom icons I'm happy to continue.

**Comment by vincentsarago** [comment]
👍

**Comment by ghost** [comment]
I'm still tweaking a few I'm not entirely happy with (sandstorm, tornado) and have to do another pass on colours (if you're happy for the current colours to be changed) but I should be ready to make a PR soon.

I was thinking of adding the icons to each disaster type via css `::before` pseudo-elements. Does that sound okay, or is there a different style you'd prefer?

**Comment by ghost** [comment]
Oh, also I've drafted two additional types; avalanches and disease.

Although disease epidemics themselves wouldn't be visible by satellite, the resulting responses might be, such as evacuations, aid infrastructure, etc. What do you think?

**Comment by vincentsarago** [comment]
all ok for both 👍 
I'll also add the icon on the popup (instead of the disasterwatch logo)

![capture d ecran 2016-10-16 a 15 53 56](https://cloud.githubusercontent.com/assets/10407788/19420417/e94fe124-93b8-11e6-8b34-6880983b71be.png)

**Comment by vincentsarago** [comment]
@CodeMacabre Man I love your icons! they are really greats 

![capture d ecran 2016-10-21 a 22 10 44](https://cloud.githubusercontent.com/assets/10407788/19616192/3e44857e-97db-11e6-9e04-8fb9a287db64.png)

FYI! I choose this the background-image solution for the css (inside a size-defined element): 
`.icon-fire {
    background-image: url('../img/fire.svg');
}`

only one comment, I'm not quite sure about the man-made icon! can we work together on this one ?

**Comment by vincentsarago** [comment]
@CodeMacabre I also modified the tornado svg because it was too heavy (430ko) 

![capture d ecran 2016-10-22 a 00 24 29](https://cloud.githubusercontent.com/assets/10407788/19616888/fb311d02-97ed-11e6-8f9b-47dfd6db65ea.png)

**Comment by ghost** [comment]
@vincentsarago 😃 Glad you like them! I'm pleased with how they look in action.

I agree the manmade one needs some work; the nuclear symbol doesn't really match the others (apart from disease, but that might need changing too). I had a couple of other ideas; either a few barrels with an oil puddle, or possibly an oil well? I think it'd work better reverting it back to black, too.

![img_20161022_160315 31](https://cloud.githubusercontent.com/assets/19981049/19620399/79388402-9874-11e6-9873-aaac6d3067b1.jpg)

The tornado was my least favourite tbh; if you want me to take another pass and try to keep the filesize down, I'm happy to work on it.

**Comment by vincentsarago** [comment]
@CodeMacabre Love your hand sketch :D 

About the man-made I had couple of ideas:
- boot trace (like the trace on the moon)
- simple human body 
- simple human hand

**Comment by vincentsarago** [comment]
@CodeMacabre about rendering icons on the map! it might be a bit difficult. Mapbox-gl require a specific svg format: https://www.mapbox.com/maki-icons/guidelines/#specs

**Comment by ghost** [comment]
@vincentsarago Hmm, yeah the icons would need to be completely redesigned to fit the Maki guidelines. I could certainly look at simplifying them all if you'd like to try it out.

I'll work on the manmade icon. The body and hand would be best if we follow the Maki guidelines, but I love the idea of the moon boot footprint. I'll try all three.

**Comment by vincentsarago** [comment]
Yeah! don't loose time on the Maki icon for now.
Thanks

**Comment by vincentsarago** [comment]
@CodeMacabre As soon as we change the man-made icon I'll do an official launch of the project!

**Comment by ghost** [comment]
Awesome! I'll work on it tomorrow send a PR on Tuesday.

**Comment by ghost** [comment]
Sent my PR #35 which includes a few minor changes along with the new manmade icon. The boot / footprint wasn't very readable at small sizes, so I went for the hand design. I tweaked the colours and changed manmade to a black / dark grey.

One major change is the svg file sizes: I realised what was making the tornado so much larger and adjusted all other icons to match. File sizes went from an average of 100kb to max 3.78kb!

**Comment by vincentsarago** [comment]
will merge now!
