### ISSUE TITLE
Database

### ISSUE THREAD

**Issue by vincentsarago** [vincentsarago/disasterwatch#22]
Up to now I have set up function to read/write/update a geojson file for a disaster database. 
Thinking about it this might be a really bad idea in the case where 2 users will add an event a the same time.

Solution: Using a proper database (elasticsearch ?) might be the best way to manage that.

**Comment by vincentsarago** [comment]
I've started to deploy a postgres server on AWS RDS !

**Comment by vincentsarago** [comment]
I've started to deploy a postgres database on AWS RDS !

**Comment by vincentsarago** [comment]
The more and more I'm working on that, the more question I have :-( 
Today thinking is: 

On person added/register to an event in the database, then someone (or himself) make a modification to the event... what now? 
- [ ] Should the user receive a mail saying the event has been updated/removed ?
- [ ] Should I restrict the deletion of an event only to the person who added the event in the first place (how to do that ?) 

I feel the best way to handle everything will be to create account (but I really don't want to do that)

**Comment by ghost** [comment]
I think the notification email would be the best of the two options, especially as you already have the functionality for users to receive emails.

Depending on your long-term goals for Disasterwatch, adding user accounts are probably not necessary at this stage. As far as I can see, the only benefit to user accounts would be to:
- track changes, wiki-style
- peer-review or moderate major edits / deletions
- prevent spam (is this already managed?)

**Comment by vincentsarago** [comment]
@CodeMacabre in my last commit I've added the new database API (mongoDB)
I'm going to work on the Emailing function and see how things work together 

I agree with you about not adding account, I see disasterwatch like an open space with self moderation.

**Comment by vincentsarago** [comment]
Summary:
I've chosen to use MongoDB on mlab (https://mlab.com) as there is a free db hosting plan.
the db is not replicated so it might not be the safer plan, but this is just for testing! 

I'm using aws lambda for the CRUD operations [disasterwatch-lambda](https://github.com/RemotePixel/disasterwatch-lambda/tree/master/database)

6 methods are defined now : 
- add : add event
- remove : remove event
- update : update event
- subscribe : subscribe to receive mail when new image is available
- unsubscribe : unsubscribe to event
- toGEOJSON : convert db to GeoJSON

As discuss previously, I'll add some mail function to inform people about any edit on the event.

I may also add a counter, to render on the UI how many people are following an event

**Comment by vincentsarago** [comment]
done!
