### ISSUE TITLE
Overlay labels on satellite basemap

### ISSUE THREAD

**Issue by TheMapSmith** [vincentsarago/disasterwatch#26]
I'd suggest swapping out the reference labels when the satellite basemaps are on. The light grey with white halos are difficult to read, and the solid black labels are also difficult. 

![image](https://cloud.githubusercontent.com/assets/8357118/19349018/df697388-911e-11e6-97a8-a3428e1a52d9.png)

**Comment by vincentsarago** [comment]
good point, I've change to black but forgot the cities!
I wasn't sure about the color (black) neither! 

I'll work on that later :-)
