### ISSUE TITLE
Imagery date and opacity

### ISSUE THREAD

**Issue by TheMapSmith** [vincentsarago/disasterwatch#27]
It seems like the imagery date is one of the most important controls when using this app. I'd suggest making this control popup at the bottom of the screen when an imagery basemap is selected. Maybe a date slider?

![image](https://cloud.githubusercontent.com/assets/8357118/19349080/377c38e4-911f-11e6-8618-56b853e2a26e.png)

I'm also not quite sure about the reason for having an imagery opacity control. The Mapbox basemap underneath is so simple I'm not sure what it's supposed to help show the user.

**Comment by vincentsarago** [comment]
good point about externalizing this part! 

the opacity is just an option, user may or may not use it (I do set it to 50% when using it)

**Comment by vincentsarago** [comment]
closed in #30
