### ISSUE TITLE
Popup Disaster Type onfocus

### ISSUE THREAD

**Issue by TheMapSmith** [vincentsarago/disasterwatch#28]
I didn't realize the first few times I used the Add to Database form that the Disaster Type box was a select dropdown. It would be nice to give a visual indication of this in some way, like the traditional "down triangle." Also, you could have it popup using the `onfocus=` event

![image](https://cloud.githubusercontent.com/assets/8357118/19349815/0feb4618-9123-11e6-91c1-a451eff40c71.png)

**Comment by vincentsarago** [comment]
will do :-)

**Comment by ghost** [comment]
Just to note, the disaster type list appears on-click (in Firefox and IE / Edge at least; Chrome is acting up for some reason), but not when focused such as via tabbing to the field.

For the arrow, I'd propose either using Unicode black down-pointing triangle ▼ (`&#9660;`) or less-than and greater-than signs <> (`&#60; &#62;`) rotated 90 degrees.

I'm happy to take these on.

**Comment by vincentsarago** [comment]
thanks @CodeMacabre !
I'll make it because this imply some change in multiple function. 
:-)

**Comment by vincentsarago** [comment]
done ! https://github.com/RemotePixel/disasterwatch/commit/a0ea200d8ecbd843d716a339a5810338e8333d37
![capture d ecran 2016-10-13 a 21 15 44](https://cloud.githubusercontent.com/assets/10407788/19372515/d13aa022-918a-11e6-851d-1a81c0214e9f.png)
